---
# Main Nornir configuration file

inventory:
  plugin: SimpleInventory
  options:
    host_file: "examples/conf/hosts.yaml"
    group_file: "examples/conf/groups.yaml"
    defaults_file: "examples/conf/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 100

logging:
  enabled: false
