inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventory/hosts.yaml"
    group_file: "inventory/groups.yaml"
    defaults_file: "inventory/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 20

logging:
  enabled: true
  level: INFO
  log_file: "nornir.log"
  to_console: true

user_defined:
  connection_options:
    napalm:
      extras:
        timeout: 60
        optional_args:
          global_delay_factor: 2
    netmiko:
      extras:
        timeout: 120
        session_timeout: 60
        auth_timeout: 30
